language:
  - cpp
  
before_install:
  - pip install --user cpp-coveralls
  
addons:
  sonarcloud:
    organization: "fiicksesh-github"
    token:
      secure: "33b0cd812c96e5e357675c645b1c6b358e4d6c7d"

script:
  - qmake
  - make
  - ./tests/tests
  
after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner
  
cache:
  directories:
    - '$HOME/.sonar/cache'
  
notifications:
  email: false
